export default [
  {
    "documentation_uri": "http://www.rubydoc.info/gems/cake/0.6.3",
    "metadata": {},
    "homepage_uri": "http://github.com/ninjudd/cake",
    "bug_tracker_uri": null,
    "project_uri": "https://rubygems.org/gems/cake",
    "version": "0.6.3",
    "sha": "6881a92b150fe659338a3581329d5929e7a771ff5749b8abca30cdb1b147b375",
    "platform": "ruby",
    "changelog_uri": null,
    "source_code_uri": null,
    "licenses": null,
    "gem_uri": "https://rubygems.org/gems/cake-0.6.3.gem",
    "downloads": 150214,
    "mailing_list_uri": null,
    "name": "cake",
    "wiki_uri": null,
    "version_downloads": 9247,
    "authors": "Justin Balthrop, Lance Bradley",
    "info": "Save your fork, there's cake!"
  },
  {
    "documentation_uri": "http://www.rubydoc.info/gems/soapy_cake/2.2.6",
    "metadata": {},
    "homepage_uri": "http://ad2games.com",
    "bug_tracker_uri": "",
    "project_uri": "https://rubygems.org/gems/soapy_cake",
    "version": "2.2.6",
    "sha": "4e439747afb89e90daad64c9f327eedc15c17e5f127c9f17dc55b0a43fd4e723",
    "platform": "ruby",
    "changelog_uri": null,
    "source_code_uri": "https://github.com/ad2games/soapy_cake",
    "licenses": [
      "MIT"
    ],
    "gem_uri": "https://rubygems.org/gems/soapy_cake-2.2.6.gem",
    "downloads": 79990,
    "mailing_list_uri": "",
    "name": "soapy_cake",
    "wiki_uri": "",
    "version_downloads": 438,
    "authors": "ad2games GmbH",
    "info": "Simple client for the CAKE API (http://getcake.com)"
  },
  {
    "documentation_uri": "http://www.rubydoc.info/gems/bucket_cake/6.3.2",
    "metadata": {},
    "homepage_uri": "https://github.com/ad2games/bucket_cake",
    "bug_tracker_uri": null,
    "project_uri": "https://rubygems.org/gems/bucket_cake",
    "version": "6.3.2",
    "sha": "31da94b04768114f5260d9abb8d9b676f02bb11d1aea0df5e91b207ba470df77",
    "platform": "ruby",
    "changelog_uri": null,
    "source_code_uri": null,
    "licenses": [
      "MIT"
    ],
    "gem_uri": "https://rubygems.org/gems/bucket_cake-6.3.2.gem",
    "downloads": 22372,
    "mailing_list_uri": null,
    "name": "bucket_cake",
    "wiki_uri": null,
    "version_downloads": 110,
    "authors": "ad2games developers",
    "info": "Get cakeproto objects from S3."
  },
  {
    "documentation_uri": "https://github.com/joshuairl/capistrano-cake",
    "metadata": {},
    "homepage_uri": "https://github.com/joshuairl/capistrano-cake",
    "bug_tracker_uri": "https://github.com/joshuairl/capistrano-cake/issues",
    "project_uri": "https://rubygems.org/gems/capistrano-cake",
    "version": "0.0.5",
    "sha": "c5d9749cfe744cdfcec22893f5f483790e3add1c0fce8d34992ded1722feaf83",
    "platform": "ruby",
    "changelog_uri": null,
    "source_code_uri": "https://github.com/joshuairl/capistrano-cake",
    "licenses": [
      "MIT"
    ],
    "gem_uri": "https://rubygems.org/gems/capistrano-cake-0.0.5.gem",
    "downloads": 6310,
    "mailing_list_uri": "",
    "name": "capistrano-cake",
    "wiki_uri": "https://github.com/joshuairl/capistrano-cake",
    "version_downloads": 1947,
    "authors": "Joshua F. Rountree, Justin Slamka",
    "info": "CakePHP deployment for Capistrano 3.x"
  },
  {
    "documentation_uri": "http://www.rubydoc.info/gems/status_cake/0.1.2",
    "metadata": {},
    "homepage_uri": "http://github.com/coupacooke/status_cake",
    "bug_tracker_uri": null,
    "project_uri": "https://rubygems.org/gems/status_cake",
    "version": "0.1.2",
    "sha": "b66e1e38d8976f3a1fb4df1d54543267c85beff3ae5457a0958157b96e619426",
    "platform": "ruby",
    "changelog_uri": null,
    "source_code_uri": null,
    "licenses": [
      "MIT"
    ],
    "gem_uri": "https://rubygems.org/gems/status_cake-0.1.2.gem",
    "downloads": 5607,
    "mailing_list_uri": null,
    "name": "status_cake",
    "wiki_uri": null,
    "version_downloads": 3479,
    "authors": "Charles Cooke",
    "info": "Ruby gem for StatusCake API - supports basic functions on tests"
  },
  {
    "documentation_uri": "http://www.rubydoc.info/gems/cake_lie/0.0.1",
    "metadata": {},
    "homepage_uri": "",
    "bug_tracker_uri": null,
    "project_uri": "https://rubygems.org/gems/cake_lie",
    "version": "0.0.1",
    "sha": "ba4aeb2f76bc4ef07c4ebdcd562786906907954dd5f7cd5484b82eb176188d17",
    "platform": "ruby",
    "changelog_uri": null,
    "source_code_uri": null,
    "licenses": [
      "MIT"
    ],
    "gem_uri": "https://rubygems.org/gems/cake_lie-0.0.1.gem",
    "downloads": 2306,
    "mailing_list_uri": null,
    "name": "cake_lie",
    "wiki_uri": null,
    "version_downloads": 2296,
    "authors": "Robert Ross",
    "info": "Creates fake information."
  },
  {
    "documentation_uri": "http://www.rubydoc.info/gems/docker-cake/0.2.2",
    "metadata": {},
    "homepage_uri": "https://github.com/paxa/docker-cake",
    "bug_tracker_uri": null,
    "project_uri": "https://rubygems.org/gems/docker-cake",
    "version": "0.2.2",
    "sha": "fd82a904f80380103c699313a2c9f8695042e46332e3fe376d161474f4f64576",
    "platform": "ruby",
    "changelog_uri": null,
    "source_code_uri": null,
    "licenses": [
      "MIT"
    ],
    "gem_uri": "https://rubygems.org/gems/docker-cake-0.2.2.gem",
    "downloads": 1637,
    "mailing_list_uri": null,
    "name": "docker-cake",
    "wiki_uri": null,
    "version_downloads": 374,
    "authors": "Pavel Evstigneev",
    "info": "Command line program to inspect docker images size"
  },
  {
    "documentation_uri": "http://www.rubydoc.info/gems/mustermann-cake/0.4.0",
    "metadata": {},
    "homepage_uri": "https://github.com/rkh/mustermann",
    "bug_tracker_uri": null,
    "project_uri": "https://rubygems.org/gems/mustermann-cake",
    "version": "0.4.0",
    "sha": "8e0038c50f8abfb46d4af8077857d4cb502c8ad796b86cea713ae6d01c076a75",
    "platform": "ruby",
    "changelog_uri": null,
    "source_code_uri": null,
    "licenses": [
      "MIT"
    ],
    "gem_uri": "https://rubygems.org/gems/mustermann-cake-0.4.0.gem",
    "downloads": 1538,
    "mailing_list_uri": null,
    "name": "mustermann-cake",
    "wiki_uri": null,
    "version_downloads": 1534,
    "authors": "Konstantin Haase",
    "info": "Adds CakePHP style patterns to Mustermman"
  },
  {
    "documentation_uri": "http://www.rubydoc.info/gems/tweeting_cake/0.0.1",
    "metadata": {},
    "homepage_uri": "https://github.com/talltorp/tweeting_cake",
    "bug_tracker_uri": null,
    "project_uri": "https://rubygems.org/gems/tweeting_cake",
    "version": "0.0.1",
    "sha": "8e5b587830b4d5bde4b771507fe8b091da71a3a61799de0d4e0e2080a0f1c592",
    "platform": "ruby",
    "changelog_uri": null,
    "source_code_uri": null,
    "licenses": [
      "MIT"
    ],
    "gem_uri": "https://rubygems.org/gems/tweeting_cake-0.0.1.gem",
    "downloads": 1499,
    "mailing_list_uri": null,
    "name": "tweeting_cake",
    "wiki_uri": null,
    "version_downloads": 1494,
    "authors": "Tobias Talltorp",
    "info": "Make a cake tweet witha Makey Makey"
  },
  {
    "documentation_uri": "http://www.rubydoc.info/gems/gluttonberg-blog/1.0.0",
    "metadata": {},
    "homepage_uri": "http://gluttonberg.com",
    "bug_tracker_uri": null,
    "project_uri": "https://rubygems.org/gems/gluttonberg-blog",
    "version": "1.0.0",
    "sha": "ef71314ffd6ec3497fbb1e22ebde0f07cbe9207c6ae8d7f1d3fce9fb29330ff6",
    "platform": "ruby",
    "changelog_uri": null,
    "source_code_uri": null,
    "licenses": [],
    "gem_uri": "https://rubygems.org/gems/gluttonberg-blog-1.0.0.gem",
    "downloads": 1714,
    "mailing_list_uri": null,
    "name": "gluttonberg-blog",
    "wiki_uri": null,
    "version_downloads": 1709,
    "authors": "Nick Crowther, Yuri Tomanek, Abdul Rauf",
    "info": "Create integrated blogs with powerful publishing flows and user management abilities."
  },
  {
    "documentation_uri": "http://www.rubydoc.info/gems/cake_lie_syeh/0.0.1",
    "metadata": {},
    "homepage_uri": "",
    "bug_tracker_uri": null,
    "project_uri": "https://rubygems.org/gems/cake_lie_syeh",
    "version": "0.0.1",
    "sha": "c35bf090684771b20f189b79c89a21648622d3130e7f96eb36cb42dc989e3f5e",
    "platform": "ruby",
    "changelog_uri": null,
    "source_code_uri": null,
    "licenses": [
      "MIT"
    ],
    "gem_uri": "https://rubygems.org/gems/cake_lie_syeh-0.0.1.gem",
    "downloads": 2325,
    "mailing_list_uri": null,
    "name": "cake_lie_syeh",
    "wiki_uri": null,
    "version_downloads": 2315,
    "authors": "Sue Anna Yeh",
    "info": "Creates fake information"
  },
  {
    "documentation_uri": "http://www.rubydoc.info/gems/cake_lie_leyh/0.0.1",
    "metadata": {},
    "homepage_uri": "",
    "bug_tracker_uri": null,
    "project_uri": "https://rubygems.org/gems/cake_lie_leyh",
    "version": "0.0.1",
    "sha": "79bf25b1003ab18f917c665dfe3f18b9dfdfc3fe7009cf8c8fc485274d97bfee",
    "platform": "ruby",
    "changelog_uri": null,
    "source_code_uri": null,
    "licenses": [
      "MIT"
    ],
    "gem_uri": "https://rubygems.org/gems/cake_lie_leyh-0.0.1.gem",
    "downloads": 2324,
    "mailing_list_uri": null,
    "name": "cake_lie_leyh",
    "wiki_uri": null,
    "version_downloads": 2315,
    "authors": "jonathonleyh",
    "info": "Creates fake information."
  },
  {
    "documentation_uri": "http://www.rubydoc.info/gems/cake_lie_ross/0.0.1",
    "metadata": {},
    "homepage_uri": "",
    "bug_tracker_uri": null,
    "project_uri": "https://rubygems.org/gems/cake_lie_ross",
    "version": "0.0.1",
    "sha": "d339d11997041255e0ae7ce62143ca381cb0e42539b0ca9f48f9c61bcd78d052",
    "platform": "ruby",
    "changelog_uri": null,
    "source_code_uri": null,
    "licenses": [
      "MIT"
    ],
    "gem_uri": "https://rubygems.org/gems/cake_lie_ross-0.0.1.gem",
    "downloads": 2321,
    "mailing_list_uri": null,
    "name": "cake_lie_ross",
    "wiki_uri": null,
    "version_downloads": 2312,
    "authors": "Robert Ross",
    "info": "Creates fake information."
  },
  {
    "documentation_uri": "http://www.rubydoc.info/gems/cake_lie_benge/0.0.1",
    "metadata": {},
    "homepage_uri": "",
    "bug_tracker_uri": null,
    "project_uri": "https://rubygems.org/gems/cake_lie_benge",
    "version": "0.0.1",
    "sha": "9f50476cc7b83f711fb6367b892921592a05e020675698796346ee4659512a34",
    "platform": "ruby",
    "changelog_uri": null,
    "source_code_uri": null,
    "licenses": [
      "MIT"
    ],
    "gem_uri": "https://rubygems.org/gems/cake_lie_benge-0.0.1.gem",
    "downloads": 2245,
    "mailing_list_uri": null,
    "name": "cake_lie_benge",
    "wiki_uri": null,
    "version_downloads": 2237,
    "authors": "SkylerBenge",
    "info": "Creates fake information"
  },
  {
    "documentation_uri": "http://www.rubydoc.info/gems/lida/0.0.3",
    "metadata": {},
    "homepage_uri": "https://github.com/jianstm/lida",
    "bug_tracker_uri": null,
    "project_uri": "https://rubygems.org/gems/lida",
    "version": "0.0.3",
    "sha": "8499a63cc3e16454c59b12c83afba992ec2908840563309c338899db3c8aea33",
    "platform": "ruby",
    "changelog_uri": null,
    "source_code_uri": null,
    "licenses": [
      "MIT"
    ],
    "gem_uri": "https://rubygems.org/gems/lida-0.0.3.gem",
    "downloads": 929,
    "mailing_list_uri": null,
    "name": "lida",
    "wiki_uri": null,
    "version_downloads": 285,
    "authors": "Quentin Jin",
    "info": "🍰 Open current finder/xcode dir in terminal/iterm and vice versa, easy as cake!"
  },
  {
    "documentation_uri": "http://www.rubydoc.info/gems/portal/0.0.1",
    "metadata": {},
    "homepage_uri": "http://github.com/ninjudd/portal",
    "bug_tracker_uri": null,
    "project_uri": "https://rubygems.org/gems/portal",
    "version": "0.0.1",
    "sha": "3b327634a6ced5e6b45146487a1312de5fd3bb2b84ce9b423828ddbae677020a",
    "platform": "ruby",
    "changelog_uri": null,
    "source_code_uri": null,
    "licenses": null,
    "gem_uri": "https://rubygems.org/gems/portal-0.0.1.gem",
    "downloads": 2798,
    "mailing_list_uri": null,
    "name": "portal",
    "wiki_uri": null,
    "version_downloads": 2794,
    "authors": "Justin Balthrop",
    "info": "The cake is a lie!"
  },
  {
    "documentation_uri": "http://www.rubydoc.info/gems/brake/0.3.7",
    "metadata": {},
    "homepage_uri": "https://github.com/jonathanchrisp/brake",
    "bug_tracker_uri": null,
    "project_uri": "https://rubygems.org/gems/brake",
    "version": "0.3.7",
    "sha": "2da2c8c49ade55bd0a95ffb7f12616996d535876aa42b7ddb5865c5b8a7226b4",
    "platform": "ruby",
    "changelog_uri": null,
    "source_code_uri": null,
    "licenses": [
      "MIT"
    ],
    "gem_uri": "https://rubygems.org/gems/brake-0.3.7.gem",
    "downloads": 46988,
    "mailing_list_uri": null,
    "name": "brake",
    "wiki_uri": null,
    "version_downloads": 2552,
    "authors": "Ben Slaughter, Jonathan Chrisp",
    "info": "A Cucumber options parser wrapper for Rake, because, cake was already taken!"
  },
  {
    "documentation_uri": "http://rubydoc.info/github/vikhyat/StormyCloud/master/frames",
    "metadata": {},
    "homepage_uri": "https://github.com/vikhyat/StormyCloud",
    "bug_tracker_uri": "https://github.com/vikhyat/StormyCloud/issues",
    "project_uri": "https://rubygems.org/gems/stormy-cloud",
    "version": "0.2.0",
    "sha": "4c6b992c400f6bebaa3042e7d05f03a85f580e38dfe3dcaddb44799767a93fae",
    "platform": "ruby",
    "changelog_uri": null,
    "source_code_uri": "https://github.com/vikhyat/StormyCloud",
    "licenses": [],
    "gem_uri": "https://rubygems.org/gems/stormy-cloud-0.2.0.gem",
    "downloads": 11241,
    "mailing_list_uri": "",
    "name": "stormy-cloud",
    "wiki_uri": "",
    "version_downloads": 1722,
    "authors": "Vikhyat Korrapati",
    "info": "StormyCloud makes writing distributed applications in Ruby a piece of cake."
  },
  {
    "documentation_uri": "http://www.rubydoc.info/gems/appscake/0.0.3",
    "metadata": {},
    "homepage_uri": "http://appscale.cs.ucsb.edu",
    "bug_tracker_uri": null,
    "project_uri": "https://rubygems.org/gems/appscake",
    "version": "0.0.3",
    "sha": "46b389dccc8c44b45abbe1011317932c1f4d56e7a3815dcf02dc10fcb700201a",
    "platform": "ruby",
    "changelog_uri": null,
    "source_code_uri": null,
    "licenses": null,
    "gem_uri": "https://rubygems.org/gems/appscake-0.0.3.gem",
    "downloads": 8170,
    "mailing_list_uri": null,
    "name": "appscake",
    "wiki_uri": null,
    "version_downloads": 2958,
    "authors": "Hiranya Jayathilaka",
    "info": "    AppsCake provides a pretty web interface that can be used to deploy\n    AppScale over machines in Xen, KVM, Amazon EC2, or Eucalyptus. In\n    short, it makes deploying AppScale a piece of cake!\n"
  }
]